# Uncomment this line to define a global platform for your project
 platform :ios, '9.3'
# Uncomment this line if you're using Swift
 use_frameworks!
pod 'UITextField+Shake', '~> 1.1'

target 'DONDE' do

end

target 'DONDETests' do

end

target 'DONDEUITests' do

end

